### PR TITLE
fix mark all as read endpoint error

### PR DESCRIPTION
**Pull request by Rzzvaan-Muhammad**
### Previous behavior

Reference : https://www.loom.com/share/9f626fde974e42829d3611b959abf823?sid=a0ff43e2-49b7-411d-84c1-cdd6c293f6c1

### Expected behavior

Reference : https://www.loom.com/share/36e4c99eb86c40219cd5b15efc239ef3?sid=76ac2f2b-e2bc-492d-8b80-96e339c45c75

### CODE REVIEW

**Review by aziyatali — APPROVED** [review]

**Review by Jscripter-pk — APPROVED** [review]

**Comment by aziyatali** [comment]
@Jscripter-pk  Any idea why we still can't merge it. Did any change the rules?

**Comment by Jscripter-pk** [comment]
yes maybe JH have changed the rules

**Comment by JonghunYu** [comment]
I didn't change anything 

github might have some trouble

**Comment by aziyatali** [comment]
Now seem like working

**Comment by aziyatali** [comment]
not really

Screenshot 2024-05-23 at 2 50 27 PM

**Comment by JonghunYu** [comment]
I don't why but I just removed ruleset

**Pull request merged**
