### PR TITLE
chore: implemented functions

### PR DESCRIPTION
**Pull request by aziyatali**
**worklog:** in progress

### CODE REVIEW

**Comment by aziyatali** [comment]
@JonghunYu @Jscripter-pk  Please kindly review and let me know if there anything to be changed.

**Comment by JonghunYu** [comment]
@Jscripter-pk Please review this

**Review by Jscripter-pk — CHANGES_REQUESTED** [review]
@aziyatali overall it looks good but one thing that is not going to work in this is 
**useQuery**(for fetching or GET requests only) and **useMutation**(for create, update, delete)

useQuery functions gets called directly as they are used for fetching. User don't need to initiate it.
useMutation functions resturn mutate function which user make a choice to get called like when user submit form, click referesh etc.

And other thing I would suggest to look into is giving test case some better description.

**Comment by aziyatali** [comment]
@Jscripter-pk I used accordingly useQuery for _get_ and useMutation for other methods. Would you please rephrase what do you mean by this  
> one thing that is not going to work in this is
useQuery(for fetching or GET requests only) and useMutation(for create, update, delete)?

**Comment by Jscripter-pk** [comment]
@aziyatali check user.ts

**Pull request merged**
