### PR TITLE
make classes importable

### PR DESCRIPTION
**Pull request by aziyatali**
@Jscripter-pk Can we try this to import each classes separately. Also updated AsyncStorage package.

### CODE REVIEW

**Comment by Jscripter-pk** [comment]
@aziyatali not actually we have to only provide a single client that can be used. So there is no need to make classes exportable

**Comment by aziyatali** [comment]
@Jscripter-pk I think importing Kross-Client for each API request seems to heavy. I think it would be better to import Loans, Investments, Account exportable as above so package size would be smaller for performance purpose.

**Comment by Jscripter-pk** [comment]
@aziyatali yeah makes sense. Can you please update the test cases as per this pattern. As I think this is better to have seperate classes to be imported/exported

**Comment by Jscripter-pk** [comment]
@aziyatali What my concern is that when ever user import class like 
import {Loans, Investments} from 'kross-sdk';

he have to make use of it like this
```
 new Investments({
        baseURL,
        accessId,
        secretKey,
      })
``` 



```
 new Loans({
        baseURL,
        accessId,
        secretKey,
      })
```
It would be better if these classes accept client in a constructor

new Loans(client)

**Comment by aziyatali** [comment]
@Jscripter-pk Test cases has been implemented with that pattern. Can you please check!

**Pull request merged**
