### PR TITLE
add articles endpoint

### PR DESCRIPTION
**Pull request by aziyatali**
@Jscripter-pk  Categorized doc-terms and articles as general, what do you think?

### CODE REVIEW

**Comment by aziyatali** [comment]
@Jscripter-pk  After you confirm the categorizing, let me publish package before merging please

**Review by Jscripter-pk — COMMENTED** [review]
@aziyatali let's keep them docTerm then as naming is based on endpoints so that in future if things change in backend we have idea of what and where things are supposed to be changed and moreover for SDK users thing will be more predictable

**Comment by Jscripter-pk** [comment]
ah I got you. 
What If we name it Information/Info rather than General?

**Comment by aziyatali** [comment]
@Jscripter-pk  I feel like Information won't really cover doc-terms.

Later on, we might want to cumulated active loan, cumulated loan and other things related to landing page data. I feel like general would be more intuitive. 
If you think Info is better, let me carry on with Info.

**Comment by Jscripter-pk** [comment]
Let's Go with GeneralInfo as just General doesn't give much context

**Review by Jscripter-pk — APPROVED** [review]
@aziyatali also update in frontend for docTerms along with articles

**Pull request merged**
