### PR TITLE
feat: add admin api

### PR DESCRIPTION
**Pull request by limhm1396**
related: https://github.com/ninetydays/olive/pull/413
If it is approved, I will publish and merge

### CODE REVIEW

**Review by Danue1 — APPROVED** [review]
How about creating `AdminClient` and moving to this changes.

**Review by Jscripter-pk — COMMENTED** [review]
@limhm1396 overall looking good, but to make things modular and more manageable for admin specific endpoints I think it is better to create seperate client for Admin endpoint as @Danue1 suggeste

**Review by aziyatali — COMMENTED** [review]
Here is some context information:

After discussion with @ijazulrehman, we came to conclusion that exposing even the name of the admin endpoints are not good approach. 
That's why we came to the conclusion to remove them from prod docs and set password for dev/staging docs.

For admin endpoints, it would be better to directly use olive instead of adding it here. If sdk is really necessary then it would be better to add admin-sdk as private repo and publish it internally.

Moreover, as we agreed, lets remove the commits from git history.

**Comment by limhm1396** [comment]
@Jscripter-pk What do you think about @aziyatali said?

**Comment by Danue1** [comment]
@Jscripter-pk @aziyatali 
I thought about this PR.

It may be the problem is the naming like `/admin`.
But it is really the problem?
I mean, we can provide the functions for admin of third-party as partner.
The reason to think this way is, CROSS META is a separate organization from our KROSS. (at least formally.)

If you agree with this opinion, there would be nothing strange about the naming.

cc. @limhm1396

**Comment by Jscripter-pk** [comment]
@limhm1396 I think you can add in current package and get you PR approved as we are moving kross-specific things to seperate sdk for our internal use and we will keep seperate sdk for external users so if admin endpoints are kross specific we will move them to new sdk otherwise we can keep them in current one.

**Comment by ijazulrehman** [comment]
**Considerations:**

1. **Security Concerns:**
   - Exposing admin endpoints can pose significant security risks. Keeping these endpoints hidden and secure is crucial to maintaining the integrity and security of the system.

2. **Modularity and Manageability:**
   - Creating a separate `AdminClient` for admin-specific endpoints, as suggested by @Danue1 and supported by @Jscripter-pk, enhances modularity. This makes the codebase more manageable and segregates general and admin functionalities, which aligns with good software design principles.

3. **SDK Structure:**
   - Moving Kross-specific functionalities to a separate, private SDK for internal use is logical. This keeps internal operations insulated from third-party access, maintaining a clear separation of concerns.
   - By keeping admin endpoints in a dedicated, private repository, their accessibility is limited, aligning with the discussed security precautions.

4. **Organizational Separation:**
   - Even though CROSS META is formally separate from Kross, the decision to restrict admin access to internal use underscores the importance of maintaining strict control over sensitive operations.

**Conclusion:**

Given the security implications and the decision to restrict admin access to internal use only, the best course of action would be to:
- Move admin-specific endpoints to a separate, private `admin-sdk` repository. This limits their accessibility to internal users and ensures that sensitive functionalities are not exposed to third parties.

In summary, prioritizing security and maintainability while ensuring the SDK structure aligns with the organizational separation between Kross and CROSS META is essential. Moving forward with a separate `AdminClient` and dedicated internal SDK for admin functionalities is the most secure and manageable approach.

cc @Danue1  @aziyatali @Jscripter-pk @limhm1396

**Comment by Jscripter-pk** [comment]
@ijazulrehman yes as within kross sdk simplification issue we will be keeping another internal sdk for our use and moving all unnecessarily required endpoints and functions from current one.

**Pull request closed without merging**
