### PR TITLE
Modify dependencies

### PR DESCRIPTION
**Pull request by limhm1396**
- modify dependencies
- fix test code

### CODE REVIEW

**Review by Jscripter-pk — COMMENTED** [review]
@limhm1396 build seems to be breaking can you check by running **yarn build**

**Comment by Jscripter-pk** [comment]
@limhm1396 I added the node and web config. Now you can see index.node.* file to be used

**Comment by JonghunYu** [comment]
@Jscripter-pk Can you check this branch is working fine with investor's app?

**Review by Jscripter-pk — APPROVED** [review]
@JonghunYu  @limhm1396 I released version with these changes and it is working fine with app.

**Pull request merged**
