### PR TITLE
Sdk cleanup

### PR DESCRIPTION
**Pull request by Jscripter-pk**

### CODE REVIEW

**Comment by Jscripter-pk** [comment]
@limhm1396 I have released the new version with most of the cleanup it still needs some more cleaning but in the meanwhile I would ask you to give the new version a try [v2.0.6-beta.7](https://github.com/ninetydays/kross-SDK/pull/258/commits/11507d5e1da529311364d02be5e042880f6be4bb)

**Comment by Jscripter-pk** [comment]
@JonghunYu can you give your feedback on this I have kept client seperate for now as before so that sdk users have more clear understanding if you want every endpoint to be provided by single krossClient.xyz instead Loans.x, Investments.y and User.z then let me know

**Comment by aziyatali** [comment]
@Jscripter-pk  

In my opinion, once we successfully test and deploy kross-sdk in all used clients, I think we make this repo private and archive it without cleaning. It will be just part of our activity/log. In case anything would happen, we could come back the archive.

What if we create new repo for third parties from scratch. I think we may follow the same project structure design but with more general APIs.
Current one has too much APIs public and exposed including test env values. 

FYI, creating public sdk for third party firms is not urgent task and can be developed by well planning. 
When I say well planning, what APIs would third parties require from us as part of the service, as we have none, we can start with very general ones from the scratch.

**Comment by Jscripter-pk** [comment]
@aziyatali creating from scratch and same design is like re-inventing the wheel, and yeah all not required endpoints are removed from this and now this one is extremely simple for external users which serves the purpose of task. And I think we have already discussed this with you once in private messages that how I am going this way which seems more optimal to me.
And moreover public package with private repo is not a good idea as it is always better to provide users with code of the package to cross check the things.

And yeah in case of another copy of it we created for clients we will be instead generalising endpoints and updating them instead as this have become extremely simple and clear. I will also remove react-query integrations from this once I will be done with the decision of how to write test-scripts for this.

**Comment by aziyatali** [comment]
@Jscripter-pk  I think I understand your point of re-inventing the wheel. And I've agreed with this approach in the beginning which was few days back. Thinking now, I came to the conclusion that no one needed the wheel in the first place meaning we do not provide to any service to third party services. kross-meta is third party company in brackets and it still uses our db. I think we will have to change whole structure in organizational level as I discussed with Ijaz(multi-tenant architecture). That's only when we truly can provide service to third parties such as Welcome, KFTC etc.

Another powerful argument is we have too much APIs exposed without providing single service yet. I think it is security issue at some level.

If we do in the way I suggest then, it would be making this repo private and archive. And creating new public sdk with limited very general endpoint. No need for react-query. Without exposing test-env values etc.

**Comment by Jscripter-pk** [comment]
@aziyatali if you go through the changes because what you are saying is what is done in this PR simple and keeping only endpoints that @JonghunYu mentioned in the docs we create for generic endpoints.

@JonghunYu also give your opinions on this before I moved forward with writing test script after removing react-query and stuff.

**Comment by Jscripter-pk** [comment]
@limhm1396 don't try with this version and sdk as we have decided to go with releasing new package out of these changes and will remove some of endpoints to be available from sdk in favour of security and safety reasons so that external users can see them from now on.
I will let you know once I will give release for new version and sdk.

**Comment by aziyatali** [comment]
@Jscripter-pk  Closing and deleting this branch as no longer needed.

**Pull request closed without merging**
